system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.1panel.hk
  app_repo: https://apps.1panel.hk
  is_demo: false
  is_intl: true
  port: 9999
  username: admin
  password: admin123

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
